"""Update Sale, Ticket set to unique=false

Revision ID: 0629e2ef862e
Revises: c20336e3c757
Create Date: 2025-04-13 23:02:02.528628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0629e2ef862e'
down_revision = 'c20336e3c757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint('sales_id_ticket_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_unique_constraint('sales_id_ticket_key', ['id_ticket'])

    # ### end Alembic commands ###
