"""Update Ticket

Revision ID: c20336e3c757
Revises: 
Create Date: 2025-04-13 22:32:54.608362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20336e3c757'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=True))
        batch_op.alter_column('id_user',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('id_user',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('total')

    # ### end Alembic commands ###
