from .auth import AuthUserRoute
from .client.client_route import ClientRoute
from .material.material_type_route import MaterialTypeRoute
from .material.material_route import MaterialRoute
from .theme.theme_route import ThemeRoute
from .theme.subtheme_route import SubthemeRoute
from .inventory.material_inventory_route import MaterialInventoryRoute
from .inventory.inventory_route import InventoryRoute
from .print.print_model_route import PrintModelRoute
from .selling.general_prices_route import GeneralPricesRoute
from .selling.ticket_route import TicketRoute
from .selling.sales_route import SalesRoute
from .selling.error_sale_route import ErrorSaleRoute